#Options
MAX_FPS = 60
PLAYER_SPEED = 7.5
PLAYER_PROJECTILE_SPEED = 8

#Colours
WHITE               = (255,255,255)
PASTEL_PINK         = (255,209,220)
SPRITES = [["ROBOT_ANIM_1", "ROBOT_ANIM_2", "ROBOT_ANIM_3", "ROBOT_ANIM_4", "EXPLOSION_ANIM_1", "EXPLOSION_ANIM_2", 
"EXPLOSION_ANIM_3", "EXPLOSION_ANIM_4", "EXPLOSION_ANIM_5", "EXPLOSION_ANIM_6", "EXPLOSION_ANIM_7", 
"BLUE_LASER", "BLUE_CIRCLE", "BLUE_MOON", "RED_LASER", "RED_CIRCLE", "RED_MOON", "GREEN_LASER", "GREEN_CIRCLE", 
"GREEN_MOON", "PURPLE_LASER", "PURPLE_CIRCLE", "PIRPLE_MOON", "GOLD_RING", "METAL_RING", "GOLD_STAR", "METAL_STAR",
"LASER_ANIM_1", "LASER_ANIM_2", "LASER_ANIM_3", "LASER_ANIM_4", "PRE_LASER"], 
["ON_PLANE", "ON_PLANE_SHOOT_ANIMATION_1", "ON_PLANE_SHOOT_ANIMATION_2", "ON_PLANE_SHOOT_ANIMATION_3", 
"ON_PLANE_SHOOT_ANIMATION_4", "PLAYER_HITBOX", "PLAYER_PLANE", "PLAYER_PROJECTILE", "HEART"], 
["IDLE_PLAYER", "IDLE_ANIMATION_1", "IDLE_ANIMATION_2", "IDLE_ANIMATION_3", "IDLE_LOOK_ANIMATION_1", 
"IDLE_LOOK_ANIMATION_2", "IDLE_LOOK_ANIMATION_3", "IDLE_LOOK_ANIMATION_4", "IDLE_LOOK_ANIMATION_5", 
"IDLE_LOOK_ANIMATION_6", "IDLE_LOOK_ANIMATION_7", "IDLE_LOOK_ANIMATION_8"]]

ENEMYSPRITESARRAY = 0
PLAYERSPRITESARRAY = 1
PLAYERMAINSCREENSPRITESARRAY = 2

#Enemies Sprite Numbers
ROBOT               = 0
EXPLOSION           = 4
BLUE_LASER          = 11
BLUE_CIRCLE         = 12
BLUE_MOON           = 13
RED_LASER           = 14
RED_CIRCLE          = 15
RED_MOON            = 16
GREEN_LASER         = 17
GREEN_CIRCLE        = 18
GREEN_MOON          = 19
PURPLE_LASER        = 20
PURPLE_CIRCLE       = 21
PURPLE_MOON         = 22
GOLD_RING           = 23
METAL_RING          = 24
GOLD_STAR           = 25
METAL_STAR          = 26
LASER               = 27

#Player Plane Sprite Numbers
ON_PLANE            = 0
ON_PLANE_SHOOT1     = 1
ON_PLANE_SHOOT2     = 2
ON_PLANE_SHOOT3     = 3
ON_PLANE_SHOOT4     = 4
PLAYER_HITBOX       = 5
PLANE               = 6
PLAYER_PROJECTILE   = 7
HEART               = 8

#Player Main Screen Sprite Numbers
IDLE                = 0
LOOK                = 4